// xcrun swiftc -parse-as-library other/tests/welcome-window-architecture-smoke.swift -o /tmp/iina-welcome-architecture-smoke
// /tmp/iina-welcome-architecture-smoke
import Foundation

@main struct WelcomeWindowArchitectureSmoke {
  static func main() throws {
    let welcome = try String(contentsOfFile: "iina/InitialWindowController.swift", encoding: .utf8)
    let playbackHistory = try String(contentsOfFile: "iina/PlaybackHistory.swift", encoding: .utf8)
    let thumbnailCache = try String(contentsOfFile: "iina/ThumbnailCache.swift", encoding: .utf8)
    let ffmpeg = try String(contentsOfFile: "iina/FFmpegController.m", encoding: .utf8)
    let project = try String(contentsOfFile: "iina.xcodeproj/project.pbxproj", encoding: .utf8)

    precondition(!welcome.contains("windowNibName"))
    precondition(!welcome.contains("Timer.scheduledTimer"))
    precondition(welcome.contains("IINAWelcomeWindow"))
    precondition(welcome.contains("headerView = nil"))
    precondition(welcome.contains("lastColumnOnlyAutoresizingStyle"))
    precondition(welcome.contains("InitialWindowRecentHostingCell"))
    precondition(welcome.contains("NSHostingView<InitialWindowRecentCellContent>"))
    precondition(!welcome.contains("makeRecentCell"))
    precondition(welcome.contains("NSWorkspace.didMountNotification"))
    precondition(welcome.contains("@MainActor\nprivate final class WelcomeWindowCoordinator"))
    precondition(welcome.contains("welcome-artwork-480-"))
    precondition(welcome.contains("thumbWidth: 480"))
    precondition(welcome.contains("cancelArtworkRequests()"))
    precondition(welcome.contains("WelcomeFolderClassificationCache"))
    precondition(welcome.contains("ShowFolderSnapshotStore.load"))
    precondition(welcome.contains("ShowFolderSnapshotStore.loadCards"))
    precondition(welcome.contains("ShowFolderSnapshotStore.save"))
    precondition(welcome.contains("WelcomeRecentSnapshotStore.load"))
    precondition(welcome.contains("WelcomeRecentSnapshotStore.save"))
    precondition(welcome.contains("restoreWelcomeSnapshot()"))
    precondition(welcome.contains("private let recentDocumentsQueue"))
    precondition(welcome.contains("case .unavailable where cachedFolderPaths.contains"))
    precondition(welcome.contains("if openLeftmostShowFolderCard()"))
    precondition(welcome.contains("guard let show = showFolders.first else { return false }"))
    precondition(welcome.contains("private static let maximumShowFolderCount = 20"))
    precondition(welcome.contains("private static let maximumRecentDocumentCount = 20"))
    precondition(welcome.contains("let cutoffDate = now.addingTimeInterval(-ShowFolder.inactivityInterval)"))
    precondition(welcome.contains(".filter { $0.addedDate >= cutoffDate }"))
    precondition(welcome.contains(".prefix(Self.maximumShowFolderCount)"))
    precondition(welcome.contains(".prefix(Self.maximumRecentDocumentCount)"))
    precondition(welcome.contains("cards = Array(cards.prefix(Self.maximumShowFolderCount))"))
    precondition(welcome.contains("guard urls.count < Self.maximumRecentDocumentCount else { return }"))
    precondition(playbackHistory.contains("KeyBookmark"))
    precondition(playbackHistory.contains("URL(resolvingBookmarkData:"))
    precondition(playbackHistory.contains("ThumbnailCache.uniquelyRenamedVideo"))
    precondition(playbackHistory.contains("var mpvProgress: VideoTime? {"))
    precondition(!playbackHistory.contains("self.mpvProgress ="))
    precondition(!playbackHistory.contains("_ = resolvedURL()"))
    precondition(thumbnailCache.contains("guard match == nil else { return nil }"))
    let shelfAccessoryStart = welcome.range(of: "private func configureShelfAccessory()")!.lowerBound
    let shelfAccessoryEnd = welcome.range(of: "override func showWindow", range: shelfAccessoryStart..<welcome.endIndex)!.lowerBound
    let shelfAccessory = welcome[shelfAccessoryStart..<shelfAccessoryEnd]
    precondition(!shelfAccessory.contains("recentScrollView.leadingAnchor"))
    precondition(!shelfAccessory.contains("recentScrollView.trailingAnchor"))
    precondition(shelfAccessory.contains("showFolderHeader.widthAnchor.constraint(equalToConstant: 400)"))
    precondition(shelfAccessory.contains("recentFilesHeader.widthAnchor.constraint(equalToConstant: 400)"))
    precondition(welcome.contains("layoutAttribute = .bottom"))
    precondition(welcome.contains("automaticallyAdjustsSize = false"))
    precondition(!welcome.contains("layoutAttribute = .top"))
    precondition(welcome.contains("let recentRowsTop = accessoryHeight + recentHeaderHeight + 12"))
    precondition(welcome.contains("recentScrollViewTopConstraint?.constant = recentRowsTop"))
    precondition(!welcome.contains("recentScrollView.topAnchor.constraint(equalTo: mainView.topAnchor),"))
    precondition(welcome.contains("NSEdgeInsets(top: 0"))
    precondition(ffmpeg.contains("atTime:(double)time"))
    precondition(ffmpeg.contains("hasRequestedTime"))
    precondition(ffmpeg.contains("cancelThumbnailGeneration"))
    precondition(ffmpeg.contains("operation.isCancelled"))
    precondition(!project.contains("InitialWindowController.xib in Resources"))
    print("PASS: welcome window is programmatic, event-driven, and uses a dedicated sharp FFmpeg artwork source.")
  }
}
