name: Spelling

on:
  push:
      branches: [swift]
  pull_request:
      branches: [swift]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: crate-ci/typos@master
