name: Spelling

on:
  push:
      branches: [meh]
  pull_request:
      branches: [meh]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: crate-ci/typos@master
